### ISSUE TITLE
[Bug] Caps lock LED bugs out when used with an animated profile

### ISSUE THREAD

**Issue by jmarmstrong1207** [OpenAnnePro/AnnePro2-Shine#33]
As what the title says. The LEDs freeze in many different ways. It usually freezes as one row of red, or none at all. The workaround is to turn off, then turn on the LEDs.

**Comment by thomazmoura** [comment]
It should be (mostly) fixed with the PR !32

**Comment by jmarmstrong1207** [comment]
Fixed
