### ISSUE TITLE
[Feature Request] Allow option to have LEDs on or off by default, and a default LED profile 

### ISSUE THREAD

**Issue by jmarmstrong1207** [OpenAnnePro/AnnePro2-Shine#35]
Currently, the LEDs are off by default and the first element in the profile array is the default profile. I wonder if it's possible to use Make to do this during compilation.

**Comment by Codetector1374** [comment]
technically "yes" but I don't think this is an elegant solution. If you really want you can make QMK send a set profile command after LED init

**Comment by jmarmstrong1207** [comment]
Makes sense. It seems like a much better solution would to just have the default keymap have commented out code for simple stuff like this to make it easier to customize. Basically better documentation
