### ISSUE TITLE
Flickering with static profile and several colours. C18

### ISSUE THREAD

**Issue by dutchgecko** [OpenAnnePro/AnnePro2-Shine#36]
I'm new to trying this out, so my apologies if I've missed something obvious.

I've loaded a custom profile without animation onto my board, but I am getting quite heavy flickering as a result. The board is a C18 model.

The profile can be viewed in my fork: https://github.com/dutchgecko/AnnePro2-Shine/commit/5a9a3ee43da05efba9555a31b5c1d3958dc17686

The supplied "Miami Nights" profile also shows some flickering, but less so than the above. The "plain" profiles with just one colour show no flickering at all.

Any suggestions as to what could be the cause?

As an aside, I tried loading this profile in as an array local to the `sunset()` function (as visible from the commented code) but this caused the keyboard to crash. I assume this is because of limited stack memory, but I thought I'd mention it.

**Comment by garrett** [comment]
I'm getting flickering with recent versions of shine too on my C18 board.

It started at commit cd751780554d2c7a8501b73b7a157708fdefc6e4.

(Everything looks solid—and _brighter_—at the previous commit, 5a0512bc6058313ede1ff7f6864bc8606fd134d9.)

**Comment by Codetector1374** [comment]
@kdarkhan is currently working on something I think could help with this. He is re-introducing the use of timers. Which was the original plan. Follow #40

**Comment by dutchgecko** [comment]
I've just rebuilt now #40 has been merged and the situation is much improved. The colours are brighter too.

If I reduce brightness on the keyboard then the flicker returns, and looking closely there is a tiny amount of flicker at full brightness, but for me this good enough.
