### ISSUE TITLE
Masks no longer work

### ISSUE THREAD

**Issue by robpneu** [OpenAnnePro/AnnePro2-Shine#46]
When I flashed my C18 board about 6 months ago, I enabled the mask function for caps lock (so the caps lock led would only turn on if caps lock was on). I've just gotten around to pulling down the changes since then, and while the overall performance of Shine is significantly better (well done!), I found that the masking functionality no longer works; the caps lock LED is always illuminated regardless of caps lock state)

I haven't been able to narrow down exactly where the change occurred, but I know it was sometime after "Restored Rainbow Flow effect (#20)" (commit dc189bfc2ac9d066ebb21a371b5cc84f18c17297) as it still works in that commit (in combination with my old QMK bin). If I get some time this weekend I will try to narrow it down further. I _believe_ this is an issue with Shine and not QMK, as the relevant functions (annepro2LedSetMask and annepro2LedClearMask) are still present in QMK (and they don't look to have changed on the QMK side), but I could be mistaken.

**Comment by robpneu** [comment]
I believe I've narrowed it down to the 86aa7fefde56c1cf1a3c625bb2c2d6bbcc8286e3 commit. It's working in the commit before it, 5a0512bc6058313ede1ff7f6864bc8606fd134d9. Quite a bit was done in 86aa7fefde56c1cf1a3c625bb2c2d6bbcc8286e3 so I haven't yet narrowed it down to what exactly in that commit caused it.

**Comment by firatakandere** [comment]
It works fine for me currently, is this still relevant?

**Comment by robpneu** [comment]
I believe this is resolved now. No idea when it was fixed but when I brought in newer changes a few weeks ago, it was working. I'd forgotten I'd opened this issue, so I'll just close it with this comment.
