### ISSUE TITLE
A buffer overwrite in function setLedRow

### ISSUE THREAD

**Issue by XinDistance** [OpenAnnePro/AnnePro2-Shine#57]
In file source/commands.c

static inline void setStickyRow(const message_t *msg) {
  setLedRow(ledSticky, msg);
  handleStickyEnabled();
}

the number of elements for ledSticky is 70, however, in the function setLedRow,

it checks if (row > NUM_ROW). if the row is equal to 5, it continues, 

setKeyColor(&ledArray[ROWCOL2IDX(row, col)], color.rgb);

assume that we have row==5 and col is 0, it doesn't write to the ledSticky array but the data next to it. I think it should be if (row >= NUM_ROW)

Another issues are in 
static inline void unsetStickyRow(const message_t *msg);
static THD_FUNCTION(blinkerFun, arg) ;
they don't check the row and col value, causing a buffer overwrite.

These row and col value should be checked.

**Comment by XinDistance** [comment]
I think it should be  if (row >= NUM_ROW)

**Comment by Codetector1374** [comment]
Good catch, you are right, sorry missed your issue earlier, just saw #58.
