### ISSUE TITLE
Can't flash anne pro 2 shine firmware.

### ISSUE THREAD

**Issue by gufranco** [OpenAnnePro/AnnePro2-Shine#9]
Hi,

I've already flashed qmk firmware into my Anne Pro 2 and it's working flawlessly, so now I'm trying to flash shine firmware and it seems to be failing. Do you know what might be happening? Seems to be stuck...

```
sudo ./annepro2_tools -p 8009 --loosy -t led ~/Workspace/Pessoal/anne/annepro2-shine.bin
args: ArgOpts {
    vid: 0x4d9,
    pid: 0x8009,
    base: 0x4000,
    loosy: true,
    target: "led",
    file: "/home/gufranco/Workspace/Pessoal/anne/annepro2-shine.bin",
}
HID Dev: 04d9:8009 if: 0
device is Some("USB-HID IAP")

```

**Comment by gufranco** [comment]
Thanks for your kind reply, @Codetector1374. I did this several times a few minutes ago, but unfortunately, it's not working. Any ideas?

**Comment by Codetector1374** [comment]
Sorry I ran into this problem a few times and it’s often solved by trying again. Maybe try a different os? Like windows or something?

**Comment by gufranco** [comment]
@Codetector1374 I've discovered what was happening to my keyboard. I contacted Obins, as I wasn't able to flash the light processor using Obins Software too. Turns out that my keyboard was damaged, and I couldn't flash any firmware into the light processor, so I sent the PCB to China and they'll fix for me. Got a spare one and it's working flawlessly.
